# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '_pipe_main_project.ui',
# licensing of '_pipe_main_project.ui' applies.
#
# Created: Mon Jun 17 23:54:39 2019
#      by: pyside2-uic  running on PySide2 5.12.3
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_ui_main_project(object):
    def setupUi(self, ui_main_project):
        ui_main_project.setObjectName("ui_main_project")
        ui_main_project.resize(368, 338)
        ui_main_project.setMinimumSize(QtCore.QSize(368, 338))
        ui_main_project.setMaximumSize(QtCore.QSize(368, 338))
        self.centralwidget = QtWidgets.QWidget(ui_main_project)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.widget = QtWidgets.QWidget(self.frame_3)
        self.widget.setGeometry(QtCore.QRect(10, 10, 311, 241))
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.list_project_widget = QtWidgets.QListWidget(self.widget)
        self.list_project_widget.setObjectName("list_project_widget")
        QtWidgets.QListWidgetItem(self.list_project_widget)
        QtWidgets.QListWidgetItem(self.list_project_widget)
        QtWidgets.QListWidgetItem(self.list_project_widget)
        QtWidgets.QListWidgetItem(self.list_project_widget)
        self.horizontalLayout_2.addWidget(self.list_project_widget)
        self.frame_2 = QtWidgets.QFrame(self.widget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.btn_Nuke = QtWidgets.QPushButton(self.frame_2)
        self.btn_Nuke.setObjectName("btn_Nuke")
        self.gridLayout_3.addWidget(self.btn_Nuke, 2, 0, 1, 1)
        self.btn_houdini = QtWidgets.QPushButton(self.frame_2)
        self.btn_houdini.setObjectName("btn_houdini")
        self.gridLayout_3.addWidget(self.btn_houdini, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem1, 5, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_goProject = QtWidgets.QPushButton(self.frame_2)
        self.btn_goProject.setObjectName("btn_goProject")
        self.horizontalLayout.addWidget(self.btn_goProject)
        self.btn_newProject = QtWidgets.QPushButton(self.frame_2)
        self.btn_newProject.setObjectName("btn_newProject")
        self.horizontalLayout.addWidget(self.btn_newProject)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label_project_folder = QtWidgets.QLabel(self.frame_2)
        self.label_project_folder.setObjectName("label_project_folder")
        self.verticalLayout.addWidget(self.label_project_folder)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.gridLayout_3.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.btn_maya = QtWidgets.QPushButton(self.frame_2)
        self.btn_maya.setObjectName("btn_maya")
        self.gridLayout_3.addWidget(self.btn_maya, 3, 0, 1, 1)
        self.btn_pftrack = QtWidgets.QPushButton(self.frame_2)
        self.btn_pftrack.setObjectName("btn_pftrack")
        self.gridLayout_3.addWidget(self.btn_pftrack, 4, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem3, 2, 1, 1, 1)
        self.horizontalLayout_2.addWidget(self.frame_2)
        self.gridLayout_2.addWidget(self.frame_3, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        ui_main_project.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(ui_main_project)
        self.statusbar.setObjectName("statusbar")
        ui_main_project.setStatusBar(self.statusbar)

        self.retranslateUi(ui_main_project)
        QtCore.QMetaObject.connectSlotsByName(ui_main_project)

    def retranslateUi(self, ui_main_project):
        ui_main_project.setWindowTitle(QtWidgets.QApplication.translate("ui_main_project", "Project Manager", None, -1))
        __sortingEnabled = self.list_project_widget.isSortingEnabled()
        self.list_project_widget.setSortingEnabled(False)
        self.list_project_widget.item(0).setText(QtWidgets.QApplication.translate("ui_main_project", "project1", None, -1))
        self.list_project_widget.item(1).setText(QtWidgets.QApplication.translate("ui_main_project", "project2", None, -1))
        self.list_project_widget.item(2).setText(QtWidgets.QApplication.translate("ui_main_project", "project3", None, -1))
        self.list_project_widget.item(3).setText(QtWidgets.QApplication.translate("ui_main_project", "project4", None, -1))
        self.list_project_widget.setSortingEnabled(__sortingEnabled)
        self.btn_Nuke.setText(QtWidgets.QApplication.translate("ui_main_project", "Nuke", None, -1))
        self.btn_houdini.setText(QtWidgets.QApplication.translate("ui_main_project", "Houdini", None, -1))
        self.btn_goProject.setText(QtWidgets.QApplication.translate("ui_main_project", "Open Project", None, -1))
        self.btn_newProject.setText(QtWidgets.QApplication.translate("ui_main_project", "New Project", None, -1))
        self.label_project_folder.setText(QtWidgets.QApplication.translate("ui_main_project", "project folder", None, -1))
        self.btn_maya.setText(QtWidgets.QApplication.translate("ui_main_project", "Maya", None, -1))
        self.btn_pftrack.setText(QtWidgets.QApplication.translate("ui_main_project", "Pftrack", None, -1))

