# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Project_manager_NewProject.ui',
# licensing of 'Project_manager_NewProject.ui' applies.
#
# Created: Tue May 28 22:56:42 2019
#      by: pyside2-uic  running on PySide2 5.12.3
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_NewProject(object):
    def setupUi_NEW_PROJECT(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(401, 498)
        MainWindow.setMinimumSize(QtCore.QSize(401, 498))
        MainWindow.setMaximumSize(QtCore.QSize(401, 498))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.formLayout = QtWidgets.QFormLayout(self.frame_2)
        self.formLayout.setObjectName("formLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ui_projectPath = QtWidgets.QLineEdit(self.frame_2)
        self.ui_projectPath.setObjectName("ui_projectPath")
        self.horizontalLayout.addWidget(self.ui_projectPath)
        self.btn_folder_lookup = QtWidgets.QToolButton(self.frame_2)
        self.btn_folder_lookup.setObjectName("btn_folder_lookup")
        self.horizontalLayout.addWidget(self.btn_folder_lookup)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(1, QtWidgets.QFormLayout.FieldRole, spacerItem)
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setObjectName("label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.label)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.ui_clientName = QtWidgets.QLineEdit(self.frame_2)
        self.ui_clientName.setObjectName("ui_clientName")
        self.verticalLayout.addWidget(self.ui_clientName)
        self.formLayout.setLayout(3, QtWidgets.QFormLayout.FieldRole, self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.ui_projectName = QtWidgets.QLineEdit(self.frame_2)
        self.ui_projectName.setObjectName("ui_projectName")
        self.verticalLayout_2.addWidget(self.ui_projectName)
        self.formLayout.setLayout(4, QtWidgets.QFormLayout.FieldRole, self.verticalLayout_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.ui_resolution_x = QtWidgets.QSpinBox(self.frame_2)
        self.ui_resolution_x.setMaximum(5000)
        self.ui_resolution_x.setProperty("value", 1920)
        self.ui_resolution_x.setObjectName("ui_resolution_x")
        self.horizontalLayout_2.addWidget(self.ui_resolution_x)
        self.ui_resolution_y = QtWidgets.QSpinBox(self.frame_2)
        self.ui_resolution_y.setMaximum(9900)
        self.ui_resolution_y.setProperty("value", 1080)
        self.ui_resolution_y.setObjectName("ui_resolution_y")
        self.horizontalLayout_2.addWidget(self.ui_resolution_y)
        self.formLayout.setLayout(5, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.ui_fps = QtWidgets.QLineEdit(self.frame_2)
        self.ui_fps.setObjectName("ui_fps")
        self.horizontalLayout_3.addWidget(self.ui_fps)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.formLayout.setLayout(6, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_3)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.formLayout.setItem(7, QtWidgets.QFormLayout.FieldRole, spacerItem2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_6 = QtWidgets.QLabel(self.frame_2)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        self.ui_shotNumber = QtWidgets.QSpinBox(self.frame_2)
        self.ui_shotNumber.setMaximum(1200)
        self.ui_shotNumber.setProperty("value", 1)
        self.ui_shotNumber.setObjectName("ui_shotNumber")
        self.horizontalLayout_4.addWidget(self.ui_shotNumber)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.formLayout.setLayout(8, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_4)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(9, QtWidgets.QFormLayout.FieldRole, spacerItem4)
        self.ui_complete_path = QtWidgets.QLabel(self.frame_2)
        self.ui_complete_path.setObjectName("ui_complete_path")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.ui_complete_path)
        self.gridLayout_3.addWidget(self.frame_2, 0, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem5, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.ui_projectPath.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "Project path...", None, -1))
        self.btn_folder_lookup.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "Mandatory fields", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "Client Name", None, -1))
        self.ui_clientName.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "Client name..", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("MainWindow", "Project Name", None, -1))
        self.ui_projectName.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "Project name..", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("MainWindow", "Resolution", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("MainWindow", "FPS", None, -1))
        self.ui_fps.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "25", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("MainWindow", "Amount of shots", None, -1))
        self.ui_complete_path.setText(QtWidgets.QApplication.translate("MainWindow", "Complete path", None, -1))

